CREATE TABLE `hollywoodportfolio`.`PRODUCTION_COMPANY` ( `PRODUCTION_COMPANY_ID` INT(10) NOT NULL , 
`PRODUCTION_COMPANY_NAME` VARCHAR(100) NOT NULL , PRIMARY KEY (`PRODUCTION_COMPANY_ID`)) ENGINE = InnoDB;

CREATE TABLE `hollywoodportfolio`.`ACTOR_LIST` ( `ACTOR_ID` INT(10) NOT NULL AUTO_INCREMENT , 
`ACTOR_NAME` VARCHAR(100) NOT NULL , PRIMARY KEY (`ACTOR_ID`)) ENGINE = InnoDB;

CREATE TABLE `hollywoodportfolio`.`REVENUE_PER_MOVIE` ( `MOVIE_ID` INT(10) NOT NULL AUTO_INCREMENT , `PRODUCTION_COMPANY_ID` INT(10) NOT NULL , 
`MOVIE_NAME` VARCHAR(100) NOT NULL , `MOVIE_BUDGET` INT(20) NOT NULL , `MOVIE_REVENUE` INT(20) NOT NULL , PRIMARY KEY (`MOVIE_ID`)) ENGINE = InnoDB;

CREATE TABLE `hollywoodportfolio`.`ACTOR_REVENUE_PER_MOVIE` (`ACTOR_ID` INT(10) NOT NULL , 
`MOVIE_ID` INT(10) NOT NULL , `BASE_AMOUNT` INT(20) NOT NULL , `REVENUE_SHARE` FLOAT(10) NOT NULL , PRIMARY KEY (`ACTOR_ID`,`MOVIE_ID`)) ENGINE = InnoDB

CREATE TABLE `hollywoodportfolio`.`MOVIE_CHARACTERS` ( `CHARACTER_ID` AUTO_INCREMENT INT(10) NOT NULL ,
`CHARACTER_NAME` VARCHAR(100) NOT NULL , `ACTOR_ID` INT(10) NOT NULL , `MOVIE_ID` INT(10) NOT NULL , PRIMARY KEY (`CHARACTER_ID`)) ENGINE = InnoDB;

CREATE TABLE `hollywoodportfolio`.`MOVIE_SCRIPT` ( `MOVIE_ID` INT(10) NOT NULL , 
`CHARACTER_ID` INT(10) NOT NULL , `LINES_IN_THE_MOVIE` VARCHAR(100) NOT NULL ) ENGINE = InnoDB;
